version: "3.8"

services:
  web:
    image: web-prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  server:
    image: server-prod
    ports:
     - 8081:8081
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13.2-alpine
    ports:
     - 5432:5432
    env_file:
     - .env
