import type { NextConfig } from 'next'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import createNextIntlPlugin from 'next-intl/plugin'

const withNextIntl = createNextIntlPlugin()

// Legacy /media/* → Vercel Blob redirects (SEO/hotlink continuity).
// Generated by scripts/migrate-media.mjs; absent until media migration runs.
function mediaRedirects(): Array<{
  source: string
  destination: string
  permanent: boolean
}> {
  const mapPath = join(__dirname, 'scripts', 'url-map.json')
  if (!existsSync(mapPath)) return []
  const map = JSON.parse(readFileSync(mapPath, 'utf8')) as Record<string, string>
  const seen = new Set<string>()
  const redirects: Array<{ source: string; destination: string; permanent: boolean }> = []
  for (const [oldUrl, blobUrl] of Object.entries(map)) {
    if (!oldUrl.startsWith('/media/')) continue
    const source = `/${oldUrl.split('/').slice(1).map(encodeURIComponent).join('/')}`
    if (seen.has(source)) continue
    seen.add(source)
    redirects.push({ source, destination: blobUrl, permanent: true })
  }
  return redirects
}

const nextConfig: NextConfig = {
  // firebase-admin (via jwks-rsa → jose) breaks when bundled: the serverless
  // runtime hits ERR_REQUIRE_ESM. Keep it (and Prisma) as external Node
  // requires instead of letting Turbopack bundle them.
  serverExternalPackages: ['firebase-admin', '@prisma/client', 'nodemailer'],
  images: {
    // Legacy DB rows store photo URLs as free text pointing at arbitrary
    // hosts (imgur, unsplash, tour sites…), so allow any https source.
    remotePatterns: [{ protocol: 'https', hostname: '**' }],
  },
  async redirects() {
    return [
      // Old admin routes → new /admin area
      { source: '/users', destination: '/admin/users', permanent: true },
      { source: '/purchases/all', destination: '/admin/purchases', permanent: true },
      { source: '/images', destination: '/admin/media', permanent: true },
      { source: '/experiences/create', destination: '/admin/experiences/new', permanent: true },
      { source: '/experiences/:id/edit', destination: '/admin/experiences/:id', permanent: true },
      // Legacy blog slugs (apostrophes/trailing dashes) → clean static slugs
      { source: "/blogs/exploring-nizwa's-timeless-charms", destination: '/blogs/exploring-nizwas-timeless-charms', permanent: true },
      { source: "/blogs/oman's-top-5-wadis", destination: '/blogs/omans-top-5-wadis', permanent: true },
      { source: '/blogs/a-trip-to-wadi-shab-', destination: '/blogs/a-trip-to-wadi-shab', permanent: true },
      { source: "/blogs/oman's-hiking-hotspots", destination: '/blogs/omans-hiking-hotspots', permanent: true },
      { source: "/blogs/oman's-best-beaches", destination: '/blogs/omans-best-beaches', permanent: true },
      { source: "/blogs/oman's-hidden-gems", destination: '/blogs/omans-hidden-gems', permanent: true },
      ...mediaRedirects(),
    ]
  },
  async rewrites() {
    return [
      // Legacy Thawani success callback path (in-flight sessions at cutover)
      {
        source: '/server/user/purchase/success/:id',
        destination: '/api/purchase/success/:id',
      },
    ]
  },
}

export default withNextIntl(nextConfig)
