// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Blog struct {
	ID            string    `json:"id"`
	Title         string    `json:"title"`
	Description   string    `json:"description"`
	TitleAr       string    `json:"title_ar"`
	DescriptionAr string    `json:"description_ar"`
	Page          string    `json:"page"`
	PageAr        string    `json:"page_ar"`
	UserID        uuid.UUID `json:"user_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type Product struct {
	ID            string      `json:"id"`
	Kind          string      `json:"kind"`
	Title         string      `json:"title"`
	TitleAr       string      `json:"title_ar"`
	Subtitle      string      `json:"subtitle"`
	SubtitleAr    string      `json:"subtitle_ar"`
	Description   string      `json:"description"`
	DescriptionAr string      `json:"description_ar"`
	Photo         string      `json:"photo"`
	PriceBaisa    int64       `json:"price_baisa"`
	PlannedDates  []time.Time `json:"planned_dates"`
	Photos        []string    `json:"photos"`
	Longitude     float64     `json:"longitude"`
	Latitude      float64     `json:"latitude"`
	LastUpdated   time.Time   `json:"last_updated"`
}

type Purchase struct {
	ID                uuid.UUID `json:"id"`
	ProductID         string    `json:"product_id"`
	UserID            uuid.UUID `json:"user_id"`
	NumOfParticipants int32     `json:"num_of_participants"`
	Paid              bool      `json:"paid"`
	CostBaisa         int64     `json:"cost_baisa"`
	ChosenDate        time.Time `json:"chosen_date"`
	Complete          bool      `json:"complete"`
	CreatedAt         time.Time `json:"created_at"`
}

type Review struct {
	ProductID   string    `json:"product_id"`
	UserID      uuid.UUID `json:"user_id"`
	Rating      float64   `json:"rating"`
	Title       string    `json:"title"`
	Review      string    `json:"review"`
	LastUpdated time.Time `json:"last_updated"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Firstname string    `json:"firstname"`
	Lastname  string    `json:"lastname"`
	Phone     string    `json:"phone"`
	Roles     []string  `json:"roles"`
}

type UserCustomerID struct {
	UserID     uuid.UUID `json:"user_id"`
	CustomerID string    `json:"customer_id"`
}
