import type { NextConfig } from 'next'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import createNextIntlPlugin from 'next-intl/plugin'

const withNextIntl = createNextIntlPlugin()

// Legacy /media/* → Vercel Blob redirects (SEO/hotlink continuity).
// Generated by scripts/migrate-media.mjs; absent until media migration runs.
function mediaRedirects(): Array<{
  source: string
  destination: string
  permanent: boolean
}> {
  const mapPath = join(__dirname, 'scripts', 'url-map.json')
  if (!existsSync(mapPath)) return []
  const map = JSON.parse(readFileSync(mapPath, 'utf8')) as Record<string, string>
  const seen = new Set<string>()
  const redirects: Array<{ source: string; destination: string; permanent: boolean }> = []
  for (const [oldUrl, blobUrl] of Object.entries(map)) {
    if (!oldUrl.startsWith('/media/')) continue
    const source = `/${oldUrl.split('/').slice(1).map(encodeURIComponent).join('/')}`
    if (seen.has(source)) continue
    seen.add(source)
    redirects.push({ source, destination: blobUrl, permanent: true })
  }
  return redirects
}

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: '*.public.blob.vercel-storage.com' },
      { protocol: 'https', hostname: 'omanosaura.com' },
      { protocol: 'https', hostname: 'i.imgur.com' },
      { protocol: 'https', hostname: 'images.unsplash.com' },
    ],
  },
  async redirects() {
    return [
      // Old admin routes → new /admin area
      { source: '/users', destination: '/admin/users', permanent: true },
      { source: '/purchases/all', destination: '/admin/purchases', permanent: true },
      { source: '/images', destination: '/admin/media', permanent: true },
      { source: '/experiences/create', destination: '/admin/experiences/new', permanent: true },
      { source: '/experiences/:id/edit', destination: '/admin/experiences/:id', permanent: true },
      { source: '/blogs/create', destination: '/admin/blogs/new', permanent: true },
      { source: '/blogs/:id/edit', destination: '/admin/blogs/:id', permanent: true },
      ...mediaRedirects(),
    ]
  },
  async rewrites() {
    return [
      // Legacy Thawani success callback path (in-flight sessions at cutover)
      {
        source: '/server/user/purchase/success/:id',
        destination: '/api/purchase/success/:id',
      },
    ]
  },
}

export default withNextIntl(nextConfig)
